import type { Metadata } from "next";
import "./globals.css";
import UserContextProvider from "./context/UserContextProvider";
import AuthContextProvider from "./context/AuthContextProvider";
import { Toaster } from "react-hot-toast";
import ToggleTheme from "./dashboard/components/ToggleTheme";

export const metadata: Metadata = {
  title: "Base Upload",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
          />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/dashboard.png" type="image/png" />
      </head>
      <body className={`font-inter fonts-sans`}>
        <Toaster />
        <AuthContextProvider>
          <UserContextProvider>
            {children}
            <div className="ml-5 md:block hidden fixed bottom-4">
              <ToggleTheme />
            </div>
          </UserContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
